url: ''
baseurl: ''
title: 'Felix Albani Blog'

postcss:
  cache: false

exclude:
  - package.json

defaults:
  -
    scope:
      path: ""
    values:
      is_post: true # automatically set is_post=true for all posts